# fly.toml app configuration file generated for discord-steam-bot on 2023-12-01T09:24:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-steam-bot"
primary_region = "lax"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
